### Site info:
title: 妖就是妖
tagline: 积累技术，研究新科技 and 喝喝
author: Jzorrof
email: jzorrof@gmail.com
description: "技术备忘录" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Python, Java, Android"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.jzorrof.info" # the base hostname & protocol for your site
locale: zh_CN

### Personal info and site tools info:
twitter_username: jzorrof
github_username:  jzorrof
disqus_shortname: joe
favicon:     "/images/tiaopi.ico"
aboutme: # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "关于我"
      Archives: "存档"
      #Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      #Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: jzorrof
      href: http://blog.jzorrof.info
      title: tech blog
    - name: author's website
      href: http://www.jzorro.info/
      title: zhong's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
